project:
  source: root:123456@tcp(127.0.0.1:33306)/cron?charset=utf8&interpolateParams=true&&parseTime=True&loc=Local
#  source: user:password@/dbname?charset=utf8&parseTime=True&loc=Local
  #root:123456@tcp(127.0.0.1:33306)/cron?charset=utf8&interpolateParams=true&&parseTime=True&loc=Local
  max_idle_connections: 50
  max_open_connections: 10
  #20 10